### ISSUE TITLE
Protocol not supported

### ISSUE THREAD

**Issue by itsamirhn** [Mon-ius/Docker-Warp-Socks#13]
When I try to run it with docker compose, I get following error:
`Unable to access interface: Protocol not supported`
And the container exits.
 Any Idea?

**Comment by Mon-ius** [comment]
Hi amirhn

Could u plz tell more details about how you get this message and details about the remote machine. 

Remind to clean the latest docker container, before you try next time.

**Comment by Mon-ius** [comment]
Also, plz follow https://github.com/Mon-ius/Docker-Warp-Socks/issues/6#issuecomment-1497605261 and https://github.com/Mon-ius/Docker-Warp-Socks/issues/6#issuecomment-1497602912 to debug, due to the multiple version of docker-compose, using the original docker cli could help more ez to address your issue
