### ISSUE TITLE
Container not running correctly on Linux RPi-4B 6.1.25-v8+

### ISSUE THREAD

**Issue by kodbuzz** [Mon-ius/Docker-Warp-Socks#14]
The container restarts automatically a few seconds after it starts on both of my Raspberry Pi 4B, I couldn't keep up with the Log because it restarts too fast, while everything works like a charm on my ARM64 CentOS.

Additional information:
- Raspberry Pi model: 4B
- Linux distribution: RPi-4B 6.1.25-v8+
- Kernel version: #1647 SMP PREEMPT Wed Apr 26 17:39:08 BST 2023
- Architecture: aarch64

**Comment by Mon-ius** [comment]
Hi kodbuzz

Thanks for reporting it. It's wired but I can help. Can u plz follow the instruction to help debug the error?

- First, run `docker ps -a` to show your real docker env container, also there will be a string likes `9a34c3c32567`
- Second, run `docker logs 9a34c3c32567` to see what's error happens

Post the result about above operations.

- Then, try to clean  your environment by `docker stop warp_socks && docker rm warp_socks && docker rmi -f $(docker images -a -q)`
- Following the basic docker example to see if everything works fine. `docker run --privileged --restart=always -itd \
    --name warp_socks \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --sysctl net.ipv4.conf.all.src_valid_mark=1 \
    --cap-add NET_ADMIN --cap-add SYS_MODULE \
    -p 9091:9091 \
    -v /lib/modules:/lib/modules \
    monius/docker-warp-socks`

**Comment by kodbuzz** [comment]
Thank you once again for your hard work and dedication to this project.




I got this error using default settings:

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory: unknown.`

Then I skipped the line with --_sysctl net.ipv6.conf.all.disable_ipv6=0_ \ while keeping the rest lines untouched.

`docker logs <CONTAINER_ID>` brings nothing as the container restarts itself within just a couple of seconds.

Any idea?

**Comment by Mon-ius** [comment]
Hi kodbuzz

Thanks for your information. It's more like your docker installation has some issues, can u try to compile the docker with latest version from the source with IPV6 related configuration enabled? 

Also, another reasons as https://forums.docker.com/t/error-response-from-daemon-oci-runtime-create-failed-container-linux-go-starting-container-process-caused-exec-python/115382 and https://github.com/docker/cli/issues/297 discuessed, there are maybe simply because your has issues when typing the command to start the container. 

Plz, remind that sometimes you need `sudo` to run some special operation.
